apply plugin: 'com.android.application'

def getCheckedOutGitCommitHash() {
    // Read the last commit hash without using git client (maybe not available)
    try {
        def gitHash = new File(".git/logs/HEAD").readLines("UTF-8")[-1].tokenize(" ")[1]
        println("Found git hash: $gitHash")
        return gitHash
    } catch (Exception ex) {
        System.err.println("Could not read git file $ex.localizedMessage")
        return "not_found"
    }
}

def getAvailableLocales() {
    new File("app/src/main/res").list(new FilenameFilter() {
        @Override
        boolean accept(File dir, String name) {
            return name.startsWith("values-") && new File(new File(dir,name), "strings.xml").exists();
        }
    }).collect() { fold -> fold.substring("values-".length())}.join(",")
}

android {
    def signingFilePath = System.getProperty("user.home") + "/.idea/signing.gradle"
    if (new File(signingFilePath).exists()) {
        apply from: signingFilePath
    }
    buildFeatures {
        buildConfig = true
    }
    defaultConfig {
        applicationId "org.noise_planet.noisecapture"
        minSdkVersion 23
        targetSdkVersion 35
        compileSdk 35
        versionCode 66
        versionName "1.3.2"
        // Store build date in apk
        buildConfigField "long", "TIMESTAMP", System.currentTimeMillis() + "L"
        buildConfigField "String", "GITHASH", "\"${getCheckedOutGitCommitHash().toString()}\""
        buildConfigField "String", "SUPPORTEDLOCALES",  "\"${getAvailableLocales()}\""
        // Enabling multidex support.
        multiDexEnabled true

        vectorDrawables.useSupportLibrary = true

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
            if (new File(signingFilePath).exists()) {
                signingConfig signingConfigs.release
            }
        }
        debug {
            debuggable true
            testProguardFile 'proguard-rules.pro'
            if (new File(signingFilePath).exists()) {
                signingConfig signingConfigs.debug
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }
    sourceSets {
        main.java.srcDirs += '../qrtone/jwarble/src/main/java'
    }
    lint {
        abortOnError false
        disable 'MissingTranslation'
    }
    namespace 'org.noise_planet.noisecapture'
}

// For using the MPAndroidChart package
// https://github.com/PhilJay/MPAndroidChart
// Apache License, Version 2.0
task listrepos {
    doLast {
        println "Repositories:"
        project.repositories.each { println "Name: " + it.name + "; url: " + it.url }
    }
}

repositories {
    mavenCentral()
    maven {
        url "https://maven.google.com"
    }
    google()
    maven {
        url "https://jitpack.io"
    }
    maven {
        url "https://repo1.maven.org/maven2/"
    }
    mavenLocal()
}


dependencies {
    implementation libs.mpandroidchart
    implementation libs.slf4j.simple
    implementation libs.jackson.databind
    implementation libs.jackson.core

    // multithreaded FFT for realtime visualisation of spectrum only
    implementation libs.jtransforms
    implementation libs.commons.math3
    implementation libs.appcompat
    implementation libs.material
    implementation libs.vectordrawable
    implementation libs.library
    //compile 'com.android.support:multidex:1.0.0'
    // Testing-only dependencies
    // Force usage of support annotations in the test app, since it is internally used by the runner module.
    implementation libs.constraintlayout
    androidTestImplementation libs.annotation
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.rules
    androidTestImplementation libs.espresso.core
    // unit test
    testImplementation libs.robolectric
    testImplementation libs.junit
    testImplementation libs.jorbis
    implementation project(':sosfilter')
}
